language: node_js
node_js:
    - "6"
    - "10"
    - "12"

branches:
    only:
        - master

before_script:
    - command -v 2>&1 >/dev/null npx || npm install --global npx

script:
    - npm run --silent lint
    - npm run --silent test
